version: '3'
services:
  web:
    build: .
    ports:
      - "8080:5000"
    environment:
      - SPOTIFY_CLIENT_ID=your_client_id
      - SPOTIFY_CLIENT_SECRET=your_client_secret
      - SPOTIFY_REDIRECT_URI=http://localhost:8080/callback
      - MOODIFY_APP_PASSWORD=you_decide_password
